local effect = {}

effect.name = "LumiLayer"
effect.author = "AutoGenerated"
effect.version = "1.0"

effect.parameters = {
    brightness = 1.25,
    contrast = 1.15,
    saturation = 1.2,
    glow_intensity = 0.6,
    glow_radius = 8.0,
    exposure = 0.2
}

local function clamp(x, minVal, maxVal)
    if x < minVal then return minVal end
    if x > maxVal then return maxVal end
    return x
end

local function applyBrightness(color, value)
    return {
        r = clamp(color.r * value, 0, 1),
        g = clamp(color.g * value, 0, 1),
        b = clamp(color.b * value, 0, 1),
        a = color.a
    }
end

local function applyContrast(color, value)
    return {
        r = clamp((color.r - 0.5) * value + 0.5, 0, 1),
        g = clamp((color.g - 0.5) * value + 0.5, 0, 1),
        b = clamp((color.b - 0.5) * value + 0.5, 0, 1),
        a = color.a
    }
end

local function applySaturation(color, value)
    local gray = color.r * 0.299 + color.g * 0.587 + color.b * 0.114
    return {
        r = clamp(gray + (color.r - gray) * value, 0, 1),
        g = clamp(gray + (color.g - gray) * value, 0, 1),
        b = clamp(gray + (color.b - gray) * value, 0, 1),
        a = color.a
    }
end

local function applyExposure(color, value)
    local factor = math.pow(2, value)
    return {
        r = clamp(color.r * factor, 0, 1),
        g = clamp(color.g * factor, 0, 1),
        b = clamp(color.b * factor, 0, 1),
        a = color.a
    }
end

local function gaussianBlur(image, x, y, radius)
    local r, g, b, a = 0, 0, 0, 0
    local count = 0

    for i = -radius, radius do
        for j = -radius, radius do
            local px = x + i
            local py = y + j
            local sample = image:getPixel(px, py)
            if sample then
                r = r + sample.r
                g = g + sample.g
                b = b + sample.b
                a = a + sample.a
                count = count + 1
            end
        end
    end

    return {
        r = r / count,
        g = g / count,
        b = b / count,
        a = a / count
    }
end

local function blendAdd(base, glow, intensity)
    return {
        r = clamp(base.r + glow.r * intensity, 0, 1),
        g = clamp(base.g + glow.g * intensity, 0, 1),
        b = clamp(base.b + glow.b * intensity, 0, 1),
        a = base.a
    }
end

function effect.apply(image)
    local width = image:getWidth()
    local height = image:getHeight()
    local output = image:createEmpty(width, height)

    for y = 0, height - 1 do
        for x = 0, width - 1 do
            local color = image:getPixel(x, y)

            color = applyBrightness(color, effect.parameters.brightness)
            color = applyContrast(color, effect.parameters.contrast)
            color = applySaturation(color, effect.parameters.saturation)
            color = applyExposure(color, effect.parameters.exposure)

            local glow = gaussianBlur(image, x, y, effect.parameters.glow_radius)
            color = blendAdd(color, glow, effect.parameters.glow_intensity)

            output:setPixel(x, y, color)
        end
    end

    return output
end

return effect
